// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartBeat.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingReq struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dde14bd8ac1d990c, []int{0}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PingResq struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResq) Reset()         { *m = PingResq{} }
func (m *PingResq) String() string { return proto.CompactTextString(m) }
func (*PingResq) ProtoMessage()    {}
func (*PingResq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dde14bd8ac1d990c, []int{1}
}

func (m *PingResq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResq.Unmarshal(m, b)
}
func (m *PingResq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResq.Marshal(b, m, deterministic)
}
func (m *PingResq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResq.Merge(m, src)
}
func (m *PingResq) XXX_Size() int {
	return xxx_messageInfo_PingResq.Size(m)
}
func (m *PingResq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResq.DiscardUnknown(m)
}

var xxx_messageInfo_PingResq proto.InternalMessageInfo

func (m *PingResq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PingReq)(nil), "pb.PingReq")
	proto.RegisterType((*PingResq)(nil), "pb.PingResq")
}

func init() { proto.RegisterFile("heartBeat.proto", fileDescriptor_dde14bd8ac1d990c) }

var fileDescriptor_dde14bd8ac1d990c = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4d, 0x2c,
	0x2a, 0x71, 0x4a, 0x4d, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x92, 0xe6, 0x62, 0x0f, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x2d,
	0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x64, 0xb8, 0x38, 0x20, 0x92,
	0xc5, 0x58, 0x64, 0x93, 0xd8, 0xc0, 0xa6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x3c,
	0x39, 0xd9, 0x58, 0x00, 0x00, 0x00,
}
